name: Upate README

on:
  push:
  schedule:               # Run workflow automatically
    - cron: "0 */1 * * *" # Runs every hour, on the hour

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Render Template
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          # Use "profile/README.md" instead on an org profile
          writeTo: "README.md"
      - name: Push
        run: | 
          git config user.name readme-scribe 🤖
          git config user.email actions@github.com
          git add .
          git commit -m "generated profile"
          git push origin main

  # medium:
  #   runs-on: ubuntu-latest
  #   name: Fetch and Generate Medium Posts
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: GitHub Readme Blog Post Action
  #       uses: ErrorGamer2000/github-readme-blog-post-action@v1
  #       with:
  #         feed_urls: "https://medium.com/feed/@nwillc"
  #         show_feed_data: false
  #     - name: Commit changed files
  #       uses: stefanzweifel/git-auto-commit-action@v4
  #       with:
  #         commit_message: Save Generated Blog Posts
  #         skip_checkout: true
