name: Generate Blog List

on:
  push:
  schedule: # Run workflow automatically
    - cron: "0 */1 * * *" # Runs every hour, on the hour

jobs:
  medium:
    runs-on: ubuntu-latest
    name: Fetch and Generate Medium Posts
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Readme Blog Post Action
        uses: ErrorGamer2000/github-readme-blog-post-action@v1
        with:
          feed_urls: "https://medium.com/feed/@nwillc"
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save Generated Blog Posts
          skip_checkout: true
